"""Local Binary Pattern (LBP) texture feature extraction module.

Deepfake faces generated by GANs often exhibit unnatural micro-texture smoothness
or unnatural boundary repetition, captured efficiently by LBP histograms.
"""

import cv2
import numpy as np
from skimage.feature import local_binary_pattern

class TextureFeatureExtractor:
    """Extracts Local Binary Pattern (LBP) histograms across image channels."""

    def __init__(self, P: int = 24, R: int = 3, method: str = "uniform"):
        """Initialize LBP feature extractor.

        Args:
            P: Number of circularly symmetric neighbor set points.
            R: Radius of circle.
            method: LBP method ('uniform', 'default', 'ror', 'nri_uniform').
        """
        self.P = P
        self.R = R
        self.method = method
        self.num_bins = P + 2 if method == "uniform" else 256

    def extract(self, image: np.ndarray) -> np.ndarray:
        """Extract LBP histogram features from RGB or grayscale image.

        Args:
            image: Input image array (H, W, C) uint8 or float32 [0, 1].

        Returns:
            1D normalized LBP histogram feature vector.
        """
        if image.dtype != np.uint8:
            img_uint8 = np.clip(image * 255.0, 0, 255).astype(np.uint8)
        else:
            img_uint8 = image

        if img_uint8.ndim == 3:
            gray = cv2.cvtColor(img_uint8, cv2.COLOR_RGB2GRAY)
        else:
            gray = img_uint8

        lbp = local_binary_pattern(gray, self.P, self.R, method=self.method)
        hist, _ = np.histogram(lbp.ravel(), bins=self.num_bins, range=(0, self.num_bins), density=True)
        return hist.astype(np.float32)
